[package]
name = "oracle"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "pasta", "asm" ] }
ff-fft = { path = "../zexe/ff-fft", features = [ "parallel"] }

ocaml = { version = "0.18.1", optional = true }
rand = { version = "0.8.3" } # "0.7.3"
rayon = { version = "1" }

[features]

ocaml_types = [ "ocaml" ]
