[package]
name = "commitment_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "pasta", "asm" ] }
dlog_solver = { path = "../../dlog_solver" }
groupmap = { path = "../../zexe/groupmap" }
ff-fft = { path = "../../zexe/ff-fft", features = [ "parallel" ] }
ocaml = { version = "0.18.1", optional = true }
oracle = { path = "../../oracle" }
colored = "1.9.2"
rand = { version = "0.8.3" } # "0.7.3"
rand_core = { version = "0.6.2" }
rayon = { version = "1" }
blake2 = "0.7"
itertools = "0.8.2"
array-init = "0.1.1"

[features]

ocaml_types = [ "ocaml" ]
