[package]
name = "plonk_protocol_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "pasta", "asm" ] }
ff-fft = { path = "../../zexe/ff-fft", features = [ "parallel"] }
commitment_dlog = { path = "../commitment" }
plonk_circuits = { path = "../../circuits/plonk" }
ocaml = { version = "0.18.1", optional = true }
oracle = { path = "../../oracle" }
colored = "1.9.3"
rand = { version = "0.8.3" } # "0.7.3"
rand_core = { version = "0.6.2" } # "0.5"
sprs = "0.7.1"
rayon = "1.3.0"
array-init = "0.1.1"

[features]

ocaml_types = [ "ocaml" ]
